"""Test cases for content passing between Content Writer and Social Media Publisher

These tests verify that content generated by Content Writer is properly
passed to and used by Social Media Publisher.
"""

import pytest
import asyncio
from unittest.mock import Mock, AsyncMock, patch, MagicMock
from datetime import datetime, timezone
import json

# Import the modules to test
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ceo_simplified_flow import SimplifiedCEOAgent, CEOFlowState
from contentWriter.content_writer_agent import ContentWriterAgent
from social_media_publisher.sub_agents.instagram import InstagramAgent


class TestContentPassing:
    """Test suite for content passing functionality"""
    
    @pytest.fixture
    def ceo_agent(self):
        """Create a CEO agent instance for testing"""
        return SimplifiedCEOAgent()
    
    @pytest.fixture
    def mock_content_writer_response(self):
        """Mock response from Content Writer agent"""
        return {
            "success": True,
            "output": "🚀 Unlock the Power of GenAI! 🤖\n\nIT professionals, are you ready to revolutionize your workflow? GenAI is transforming how we code, debug, and innovate. From automated code generation to intelligent testing, the future is here!\n\n💡 Key Benefits:\n• 10x faster development cycles\n• Smarter debugging with AI insights\n• Automated documentation\n• Enhanced code quality\n\nJoin the AI revolution today! 🌟\n\n#GenAI #ArtificialIntelligence #ITInnovation #TechTrends #Coding #AIRevolution #FutureOfWork #TechCommunity #Programming #DigitalTransformation",
            "generated_content": "🚀 Unlock the Power of GenAI! 🤖\n\nIT professionals, are you ready to revolutionize your workflow? GenAI is transforming how we code, debug, and innovate. From automated code generation to intelligent testing, the future is here!\n\n💡 Key Benefits:\n• 10x faster development cycles\n• Smarter debugging with AI insights\n• Automated documentation\n• Enhanced code quality\n\nJoin the AI revolution today! 🌟\n\n#GenAI #ArtificialIntelligence #ITInnovation #TechTrends #Coding #AIRevolution #FutureOfWork #TechCommunity #Programming #DigitalTransformation",
            "duration_ms": 1234,
            "provider_used": "groq",
            "model_used": "mixtral-8x7b-32768"
        }
    
    @pytest.fixture
    def mock_orchestration_plan(self):
        """Mock orchestration plan with Content Writer and Social Publisher"""
        return {
            "request_id": "test-request-123",
            "mode": "sequential",
            "steps": [
                {
                    "agent_id": "content_writer",
                    "agent_name": "Content Writer",
                    "instruction": "Write an engaging Instagram post about GenAI for IT professionals.",
                    "endpoint": "/api/agents/content_writer"
                },
                {
                    "agent_id": "social_publisher",
                    "agent_name": "Social Media Publisher",
                    "instruction": "Schedule and publish the written post on Instagram at an optimal time.",
                    "endpoint": "/api/agents/social_publisher"
                }
            ]
        }
    
    def test_process_agent_response_extracts_content(self, ceo_agent):
        """Test that process_agent_response correctly extracts content from various response formats"""
        # Test case 1: Content in 'output' field
        response1 = {
            "success": True,
            "response": {
                "output": "Generated Instagram content here",
                "duration_ms": 100
            }
        }
        result1 = ceo_agent.process_agent_response(response1)
        assert result1["output"] == "Generated Instagram content here"
        
        # Test case 2: Content in 'generated_content' field
        response2 = {
            "success": True,
            "response": {
                "generated_content": "Another Instagram post",
                "duration_ms": 200
            }
        }
        result2 = ceo_agent.process_agent_response(response2)
        assert result2["output"] == "Another Instagram post"
        
        # Test case 3: Content in 'text' field
        response3 = {
            "success": True,
            "response": {
                "text": "Text field content",
                "duration_ms": 300
            }
        }
        result3 = ceo_agent.process_agent_response(response3)
        assert result3["output"] == "Text field content"
        
        # Test case 4: Content in 'content' field
        response4 = {
            "success": True,
            "response": {
                "content": "Content field text",
                "duration_ms": 400
            }
        }
        result4 = ceo_agent.process_agent_response(response4)
        assert result4["output"] == "Content field text"
    
    def test_prepare_agent_request_for_social_publisher(self, ceo_agent):
        """Test that prepare_agent_request correctly passes content to social publisher"""
        # Previous output from Content Writer
        previous_output = "🚀 Amazing GenAI content for Instagram! #AI #Tech"
        
        # Prepare request for social publisher
        request = ceo_agent.prepare_agent_request(
            agent_id="social_publisher",
            instruction="Publish the post",
            previous_output=previous_output,
            context={"previous_agent": "Content Writer"}
        )
        
        # Verify content is passed correctly
        assert request["content"] == previous_output
        assert request["caption"] == previous_output
        assert request["platform"] == "instagram"
        assert "task" in request
    
    def test_prepare_agent_request_without_previous_output(self, ceo_agent):
        """Test prepare_agent_request when no previous output is available"""
        # No previous output
        request = ceo_agent.prepare_agent_request(
            agent_id="social_publisher",
            instruction="Publish this specific text",
            previous_output=None,
            context={}
        )
        
        # Should use instruction as fallback
        assert request["content"] == "Publish this specific text"
        assert request["caption"] == "Publish this specific text"
    
    @pytest.mark.asyncio
    async def test_execute_plan_sequentially_passes_content(self, ceo_agent, mock_orchestration_plan, mock_content_writer_response):
        """Test that execute_plan_sequentially correctly passes content between agents"""
        # Mock the execute_agent method
        async def mock_execute_agent(agent_id, agent_name, endpoint, payload, session_id):
            if agent_id == "content_writer":
                return {
                    "success": True,
                    "agent_id": "content_writer",
                    "agent_name": "Content Writer",
                    "response": mock_content_writer_response
                }
            elif agent_id == "social_publisher":
                # Verify that content was passed correctly
                assert "content" in payload
                assert "caption" in payload
                assert payload["content"] == mock_content_writer_response["output"]
                assert payload["caption"] == mock_content_writer_response["output"]
                return {
                    "success": True,
                    "agent_id": "social_publisher",
                    "agent_name": "Social Media Publisher",
                    "response": {
                        "output": "Successfully published to Instagram",
                        "post_id": "ig_123456"
                    }
                }
            return {"success": False}
        
        # Replace execute_agent with mock
        ceo_agent.execute_agent = mock_execute_agent
        
        # Execute the plan
        results = await ceo_agent.execute_plan_sequentially(
            mock_orchestration_plan,
            "Polished requirements here",
            "test-session-123"
        )
        
        # Verify results
        assert len(results) == 2
        assert results[0]["agent_name"] == "Content Writer"
        assert results[0]["success"] == True
        assert results[1]["agent_name"] == "Social Media Publisher"
        assert results[1]["success"] == True
    
    @pytest.mark.asyncio
    async def test_full_content_flow_integration(self, ceo_agent):
        """Test the full content flow from Content Writer to Social Publisher"""
        # Mock HTTP client for API calls
        mock_response = Mock()
        mock_response.status_code = 200
        
        # Mock Content Writer response
        content_writer_response = {
            "output": "✨ Exciting GenAI News! Check out the latest innovations in AI... #GenAI #Innovation",
            "success": True
        }
        
        # Mock Social Publisher response
        social_publisher_response = {
            "success": True,
            "post_id": "ig_789012",
            "message": "Posted successfully"
        }
        
        async def mock_post(url, json=None, headers=None, timeout=None):
            if "content_writer" in url:
                mock_response.json = lambda: content_writer_response
            elif "social_publisher" in url:
                # Verify content was passed
                assert json["content"] == content_writer_response["output"]
                assert json["caption"] == content_writer_response["output"]
                mock_response.json = lambda: social_publisher_response
            return mock_response
        
        # Mock httpx client
        with patch('httpx.AsyncClient') as mock_client:
            mock_instance = AsyncMock()
            mock_instance.post = mock_post
            mock_client.return_value.__aenter__.return_value = mock_instance
            
            # Execute plan
            results = await ceo_agent.execute_plan_sequentially(
                {
                    "steps": [
                        {
                            "agent_id": "content_writer",
                            "agent_name": "Content Writer",
                            "instruction": "Write GenAI post",
                            "endpoint": "/api/agents/content_writer"
                        },
                        {
                            "agent_id": "social_publisher",
                            "agent_name": "Social Publisher",
                            "instruction": "Publish to Instagram",
                            "endpoint": "/api/agents/social_publisher"
                        }
                    ]
                },
                "Test requirements",
                "session-123"
            )
            
            # Verify content was passed through the chain
            assert len(results) == 2
            assert results[0]["output"] == content_writer_response["output"]
            assert results[1]["success"] == True


if __name__ == "__main__":
    # Run tests
    pytest.main([__file__, "-v"])